name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v3
      
      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install faiss-cpu

      # 4️⃣ Download NLTK data
      - name: Download NLTK data
        run: |
          python -m nltk.downloader punkt stopwords wordnet

      # 5️⃣ Run tests with proper PYTHONPATH
      - name: Run tests
        env:
          PYTHONPATH: src    # Important: points to src/ for absolute imports
        run: |
          pytest -v tests --maxfail=1 --disable-warnings
